package main

import (
	"encoding/csv"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	goodsCSV  = "tmp/regulation-bin-dump/csv/EquipParamGoods.csv"
	weaponCSV = "tmp/regulation-bin-dump/csv/EquipParamWeapon.csv"
	outputGo  = "backend/db/data/game_limits_generated.go"
)

type limits struct {
	id             uint32
	maxInventory   uint32
	maxStorage     uint32
	inventoryKnown bool
	storageKnown   bool
	source         string
}

func main() {
	rows := make(map[uint32]limits)
	mustRead(goodsCSV, func(header map[string]int, row []string) error {
		rawID, ok := nonNegative(rowAt(row, header, "Row ID"))
		if !ok || rawID > 0x0FFFFFFF {
			return nil
		}
		maxInventory, inventoryKnown := nonNegative(rowAt(row, header, "maxNum"))
		isDeposit, depositKnown := nonNegative(rowAt(row, header, "isDeposit"))
		maxRepository, repositoryKnown := nonNegative(rowAt(row, header, "maxRepositoryNum"))

		entry := limits{
			id:             0x40000000 | uint32(rawID),
			maxInventory:   uint32(maxInventory),
			inventoryKnown: inventoryKnown,
			source:         "EquipParamGoods",
		}
		switch {
		case depositKnown && isDeposit == 0:
			entry.maxStorage = 0
			entry.storageKnown = true
		case depositKnown && isDeposit == 1 && repositoryKnown:
			entry.maxStorage = uint32(maxRepository)
			entry.storageKnown = true
		}
		if entry.inventoryKnown || entry.storageKnown {
			rows[entry.id] = entry
		}
		return nil
	})

	// Ammunition uses EquipParamWeapon rather than EquipParamGoods. Regulation
	// exposes the carried limit as maxArrowQuantity. The in-game repository cap
	// for all four ammunition families is 600; isDeposit still gates whether a
	// repository value applies.
	ammoTypes := map[int64]bool{81: true, 83: true, 85: true, 86: true}
	mustRead(weaponCSV, func(header map[string]int, row []string) error {
		rawID, ok := nonNegative(rowAt(row, header, "Row ID"))
		if !ok || rawID > 0xFFFFFFFF {
			return nil
		}
		wepType, ok := nonNegative(rowAt(row, header, "wepType"))
		if !ok || !ammoTypes[wepType] {
			return nil
		}
		maxInventory, inventoryKnown := nonNegative(rowAt(row, header, "maxArrowQuantity"))
		isDeposit, depositKnown := nonNegative(rowAt(row, header, "isDeposit"))
		entry := limits{
			id:             uint32(rawID),
			maxInventory:   uint32(maxInventory),
			inventoryKnown: inventoryKnown,
			source:         "EquipParamWeapon ammo",
		}
		if depositKnown {
			entry.storageKnown = true
			if isDeposit == 1 {
				entry.maxStorage = 600
			}
		}
		if entry.inventoryKnown || entry.storageKnown {
			rows[entry.id] = entry
		}
		return nil
	})

	ids := make([]uint32, 0, len(rows))
	for id := range rows {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })

	var b strings.Builder
	b.WriteString("// Code generated by tools/generate_game_limits; DO NOT EDIT.\n\n")
	b.WriteString("package data\n\n")
	b.WriteString("// GameLimitsByItemID contains technical per-record limits sourced from\n")
	b.WriteString("// regulation.bin. Goods storage is gated by isDeposit. Ammunition storage\n")
	b.WriteString("// uses the game's fixed 600-unit repository cap.\n")
	b.WriteString("var GameLimitsByItemID = map[uint32]GameLimitData{\n")
	for _, id := range ids {
		v := rows[id]
		fmt.Fprintf(&b, "\t0x%08X: {MaxInventory: %d, MaxStorage: %d, InventoryKnown: %t, StorageKnown: %t}, // %s\n",
			id, v.maxInventory, v.maxStorage, v.inventoryKnown, v.storageKnown, v.source)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(outputGo, formatted, 0o644); err != nil {
		fatalf("write %s: %v", outputGo, err)
	}
}

func mustRead(path string, consume func(map[string]int, []string) error) {
	f, err := os.Open(filepath.Clean(path))
	if err != nil {
		fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.Comma = ';'
	r.FieldsPerRecord = -1
	headerRow, err := r.Read()
	if err != nil {
		fatalf("read header %s: %v", path, err)
	}
	header := make(map[string]int, len(headerRow))
	for i, name := range headerRow {
		header[name] = i
	}
	for {
		row, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			fatalf("read %s: %v", path, err)
		}
		if err := consume(header, row); err != nil {
			fatalf("consume %s: %v", path, err)
		}
	}
}

func rowAt(row []string, header map[string]int, name string) string {
	i, ok := header[name]
	if !ok || i >= len(row) {
		return ""
	}
	return row[i]
}

func nonNegative(raw string) (int64, bool) {
	value, err := strconv.ParseInt(strings.TrimSpace(raw), 10, 64)
	return value, err == nil && value >= 0
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
