// Code generated by tools/import_aow_compat.py; DO NOT EDIT.

package data

// AoWDLCFallbackWepTypes is the Layer 3 compatibility fallback for DLC Ashes of War
// that are not encoded in the standard or reserved canMountWep bits.
//
// Mechanism (Phase 1.6 empirical, deterministic from local CSVs):
//   1. Group EquipParamGem rows by mountWepTextId (UI tag).
//   2. Each group collects the set of swordArtsParamIds across its gems.
//   3. A weapon base row whose default swordArtsParamId is in the group's SAP-set
//      indicates the group's compatible wepType(s).
//   4. Per-AoW: emit the list of wepTypes derived from its group.
//
// Used by CheckAoWCompatibility after the standard 40-bit canMountWep check fails.
// AoW is mountable on a weapon if its wepType appears in this list.
var AoWDLCFallbackWepTypes = map[uint32][]uint16{
	0x80002710: {5},
	0x80002774: {15, 16, 25, 28, 35, 93},
	0x8000283C: {3, 9, 11, 14, 29, 31},
	0x80002904: {25, 28, 29, 41},
	0x80002968: {5, 7},
	0x800029CC: {5, 7},
	0x80002A30: {15, 16, 25, 28, 35, 93},
	0x80002A94: {15, 16, 25, 28, 35, 93},
	0x80002AF8: {3, 17, 19},
	0x80002C24: {41},
	0x80002C88: {13},
	0x80002CEC: {3},
	0x80002E18: {14},
	0x80002FA8: {25, 28, 29, 41},
	0x800050DC: {7},
	0x80005460: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x800055F0: {5},
	0x80005654: {14},
	0x80007530: {5, 65, 67, 69, 90},
	0x80007594: {5, 65, 67, 69, 90},
	0x800075F8: {1, 65, 67},
	0x80007850: {5, 65, 67, 69, 90},
	0x800078B4: {57, 61, 65, 67, 69},
	0x80009C40: {53},
	0x80009CA4: {50},
	0x80009D08: {50, 51},
	0x80009DD0: {50, 51},
	0x80009E34: {50, 51},
	0x8000C3B4: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000C418: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000C47C: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000C4E0: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000C544: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000C5A8: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000C60C: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000C6D4: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000EA60: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000EAC4: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000EB8C: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000EBF0: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000EC54: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000FDE8: {17, 19, 21, 23, 25},
	0x8000FE4C: {17, 19, 21, 23, 25},
	0x8000FEB0: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8000FF14: {7},
	0x8000FF78: {17, 19, 21, 23, 25},
	0x80011170: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x800111D4: {5, 65, 67, 69, 90},
	0x80011238: {5, 65, 67, 69, 90},
	0x80013880: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x800138E4: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x80013948: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x80014C08: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x80030D40: {88},
	0x80061E68: {88},
	0x80062250: {91},
	0x80062638: {91},
	0x800631F0: {95},
	0x800635D8: {95},
	0x80063DA8: {92},
	0x80064190: {92},
	0x80064578: {94},
	0x80064960: {93},
	0x80064D48: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x80065518: {5},
	0x80065900: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x800664B8: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x8007B4A8: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	0x80085CA0: {53},
	0x800C3500: {5, 65, 67, 69, 90},
}

// AoWMwtidGroups is a diagnostic map: mountWepTextId → list of compatible wepTypes
// derived from the matching SAP set. Useful for tests and audit; NOT used by the
// compat algorithm directly (per-AoW AoWDLCFallbackWepTypes is sufficient).
var AoWMwtidGroups = map[int32][]uint16{
	63000: {5},
	63002: {3, 9, 11, 14, 29, 31},
	63003: {5, 7},
	63004: {15, 16, 25, 28, 35, 93},
	63007: {41},
	63008: {13},
	63009: {3},
	63013: {25, 28, 29, 41},
	63024: {14},
	63031: {57, 61, 65, 67, 69},
	63032: {53},
	63033: {50, 51},
	63039: {7},
	63040: {17, 19, 21, 23, 25},
	63041: {5, 65, 67, 69, 90},
	63042: {1, 3, 17, 21, 23, 35, 37, 39, 41, 89},
	63043: {3, 17, 19},
	63047: {1, 65, 67},
	63048: {50},
	63049: {5},
	63051: {88},
	63054: {91},
	63055: {92},
	63056: {93},
	63057: {94},
	63058: {95},
}
