import {createHash} from 'node:crypto';
import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const makefile = readFileSync(resolve(repoRoot, 'Makefile'), 'utf8');
const version = (process.argv[2] || readVersionFromMakefile(makefile)).trim();

if (!version) {
  throw new Error('VERSION is empty');
}

updateJson('wails.json', data => {
  data.info = data.info || {};
  data.info.productVersion = version;
  return data;
});

updateJson('frontend/package.json', data => {
  data.version = version;
  return data;
});
syncPackageJsonMd5();

updateJson('frontend/package-lock.json', data => {
  data.version = version;
  if (data.packages && data.packages['']) {
    data.packages[''].version = version;
  }
  return data;
});

writeFileIfChanged(
  'frontend/src/version.ts',
  `// Code generated by scripts/sync-version.mjs; do not edit by hand.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`,
);

function readVersionFromMakefile(text) {
  const match = text.match(/^VERSION\s*=\s*(.+)$/m);
  return match ? match[1] : '';
}

function updateJson(relativePath, update) {
  const filePath = resolve(repoRoot, relativePath);
  if (!existsSync(filePath)) {
    return;
  }
  const data = JSON.parse(readFileSync(filePath, 'utf8'));
  const next = update(data);
  writeFileIfChanged(relativePath, `${JSON.stringify(next, null, 2)}\n`);
}

function writeFileIfChanged(relativePath, content) {
  const filePath = resolve(repoRoot, relativePath);
  const current = existsSync(filePath) ? readFileSync(filePath, 'utf8') : '';
  if (current !== content) {
    writeFileSync(filePath, content);
  }
}

function syncPackageJsonMd5() {
  const packageJsonPath = resolve(repoRoot, 'frontend/package.json');
  const md5 = createHash('md5').update(readFileSync(packageJsonPath)).digest('hex');
  writeFileIfChanged('frontend/package.json.md5', md5);
}
