//go:build ignore

// import_weights generates backend/db/data/weights.go from regulation.bin CSV dumps.
// Usage: go run tools/import_weights.go
//
// Must be run from the repository root directory.
//
// CSV sources (all in tmp/regulation-bin-dump/csv/):
//
//	EquipParamWeapon.csv    col 8  (1-indexed) = col 7  (0-indexed) — weight
//	                        saveID = rowID (direct, no offset)
//	                        covers: melee_armaments, ranged_and_catalysts, shields
//
//	EquipParamProtector.csv col 14 (1-indexed) = col 13 (0-indexed) — weight
//	                        saveID = 0x10000000 + rowID
//	                        covers: head, chest, arms, legs
//
//	EquipParamAccessory.csv col 7  (1-indexed) = col 6  (0-indexed) — weight
//	                        saveID = 0x20000000 + rowID
//	                        covers: talismans

package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"
)

type entry struct {
	id     uint32
	weight float64
}

func readCSV(path string, weightCol int, idOffset uint32) []entry {
	f, err := os.Open(path)
	if err != nil {
		log.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.Comma = ';'
	r.LazyQuotes = true

	if _, err := r.Read(); err != nil {
		log.Fatalf("read header %s: %v", path, err)
	}

	var out []entry
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Printf("warn: %v", err)
			continue
		}
		if len(rec) <= weightCol {
			continue
		}
		rowID, err := strconv.ParseUint(strings.TrimSpace(rec[0]), 10, 32)
		if err != nil {
			continue
		}
		wStr := strings.TrimSpace(rec[weightCol])
		if wStr == "" {
			continue
		}
		w, err := strconv.ParseFloat(wStr, 64)
		if err != nil || w <= 0 {
			continue
		}
		out = append(out, entry{id: uint32(rowID) + idOffset, weight: w})
	}
	return out
}

func main() {
	base := "tmp/regulation-bin-dump/csv"
	entries := readCSV(base+"/EquipParamWeapon.csv", 7, 0)                                // saveID = rowID
	entries = append(entries, readCSV(base+"/EquipParamProtector.csv", 13, 0x10000000)...) // saveID = 0x10000000 + rowID
	entries = append(entries, readCSV(base+"/EquipParamAccessory.csv", 6, 0x20000000)...)  // saveID = 0x20000000 + rowID

	seen := map[uint32]bool{}
	unique := make([]entry, 0, len(entries))
	for _, e := range entries {
		if !seen[e.id] {
			seen[e.id] = true
			unique = append(unique, e)
		}
	}
	sort.Slice(unique, func(i, j int) bool { return unique[i].id < unique[j].id })

	out, err := os.Create("backend/db/data/weights.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "package data")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "// ItemWeights maps base item ID to weight in kg.")
	fmt.Fprintln(out, "// Auto-generated by tools/import_weights.go — do not edit.")
	fmt.Fprintln(out, "var ItemWeights = map[uint32]float64{")
	for _, e := range unique {
		fmt.Fprintf(out, "\t0x%08X: %g,\n", e.id, e.weight)
	}
	fmt.Fprintln(out, "}")

	fmt.Printf("Generated backend/db/data/weights.go — %d entries\n", len(unique))
}
