//go:build ignore

// import_sort_ids generates backend/db/data/sort_ids.go from regulation.bin CSV dumps.
// Usage: go run tools/import_sort_ids.go
//
// Must be run from the repository root directory.
//
// CSV sources (all in tmp/regulation-bin-dump/csv/):
//
//	EquipParamWeapon.csv    col  5 (0-indexed) = sortId
//	                        col 182 (0-indexed) = sortGroupId
//	                        saveID = rowID (direct, no offset)
//	                        covers: melee_armaments, ranged_and_catalysts, shields
//
//	EquipParamProtector.csv col  4 (0-indexed) = sortId
//	                        col 74 (0-indexed) = sortGroupId
//	                        saveID = 0x10000000 + rowID
//	                        covers: head, chest, arms, legs
//
//	EquipParamAccessory.csv col 10 (0-indexed) = sortId
//	                        col 22 (0-indexed) = sortGroupId
//	                        saveID = 0x20000000 + rowID
//	                        covers: talismans
//
// Rows with sortId == 0 are skipped (unused/deleted entries).
// Rows with sortId == 9999999 are kept — they sort to the end in-game.

package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"
)

type sortEntry struct {
	id          uint32
	sortID      uint32
	sortGroupID uint8
}

func readSortCSV(path string, sortIDCol, sortGroupIDCol int, idOffset uint32) []sortEntry {
	f, err := os.Open(path)
	if err != nil {
		log.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.Comma = ';'
	r.LazyQuotes = true

	if _, err := r.Read(); err != nil {
		log.Fatalf("read header %s: %v", path, err)
	}

	maxCol := sortIDCol
	if sortGroupIDCol > maxCol {
		maxCol = sortGroupIDCol
	}

	var out []sortEntry
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Printf("warn: %v", err)
			continue
		}
		if len(rec) <= maxCol {
			continue
		}

		rowID, err := strconv.ParseUint(strings.TrimSpace(rec[0]), 10, 32)
		if err != nil {
			continue
		}

		sidStr := strings.TrimSpace(rec[sortIDCol])
		if sidStr == "" {
			continue
		}
		sid, err := strconv.ParseUint(sidStr, 10, 32)
		if err != nil || sid == 0 {
			continue
		}

		sgidStr := strings.TrimSpace(rec[sortGroupIDCol])
		if sgidStr == "" {
			continue
		}
		sgid, err := strconv.ParseUint(sgidStr, 10, 16)
		if err != nil {
			continue
		}

		out = append(out, sortEntry{
			id:          uint32(rowID) + idOffset,
			sortID:      uint32(sid),
			sortGroupID: uint8(sgid),
		})
	}
	return out
}

func main() {
	base := "tmp/regulation-bin-dump/csv"
	entries := readSortCSV(base+"/EquipParamWeapon.csv", 5, 182, 0)                                // saveID = rowID
	entries = append(entries, readSortCSV(base+"/EquipParamProtector.csv", 4, 74, 0x10000000)...)  // saveID = 0x10000000 + rowID
	entries = append(entries, readSortCSV(base+"/EquipParamAccessory.csv", 10, 22, 0x20000000)...) // saveID = 0x20000000 + rowID

	seen := map[uint32]bool{}
	unique := make([]sortEntry, 0, len(entries))
	for _, e := range entries {
		if !seen[e.id] {
			seen[e.id] = true
			unique = append(unique, e)
		}
	}
	sort.Slice(unique, func(i, j int) bool { return unique[i].id < unique[j].id })

	out, err := os.Create("backend/db/data/sort_ids.go")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "package data")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "// ItemSortKeys maps base item ID to its in-game sort key.")
	fmt.Fprintln(out, "// Auto-generated by tools/import_sort_ids.go — do not edit.")
	fmt.Fprintln(out, "var ItemSortKeys = map[uint32]SortKey{")
	for _, e := range unique {
		fmt.Fprintf(out, "\t0x%08X: {SortId: %d, SortGroupId: %d},\n", e.id, e.sortID, e.sortGroupID)
	}
	fmt.Fprintln(out, "}")

	fmt.Printf("Generated backend/db/data/sort_ids.go — %d entries\n", len(unique))
}
