// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInventoryWorkspaceItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddInventoryWorkspaceItem'](arg1, arg2, arg3, arg4);
}

export function AddItemsToCharacter(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddItemsToCharacter'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddItemsToCharacterWithGameLimits(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddItemsToCharacterWithGameLimits'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AnalyzeGaItemDuplicate(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeGaItemDuplicate'](arg1, arg2);
}

export function AnalyzeGaItemRepack(arg1) {
  return window['go']['main']['App']['AnalyzeGaItemRepack'](arg1);
}

export function ApplyBuildTemplateFromLibrary(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyBuildTemplateFromLibrary'](arg1, arg2, arg3);
}

export function ApplyBuildTemplateV2FromFileToCharacter(arg1, arg2) {
  return window['go']['main']['App']['ApplyBuildTemplateV2FromFileToCharacter'](arg1, arg2);
}

export function ApplyBuildTemplateV2FromLibraryToCharacter(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyBuildTemplateV2FromLibraryToCharacter'](arg1, arg2, arg3);
}

export function ApplyBuildTemplateV2ToCharacterJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyBuildTemplateV2ToCharacterJSON'](arg1, arg2, arg3);
}

export function ApplyBuiltinCharacterPresetInventory(arg1, arg2) {
  return window['go']['main']['App']['ApplyBuiltinCharacterPresetInventory'](arg1, arg2);
}

export function ApplyBuiltinCharacterPresetStats(arg1, arg2) {
  return window['go']['main']['App']['ApplyBuiltinCharacterPresetStats'](arg1, arg2);
}

export function ApplyMirrorFavoriteToCharacter(arg1, arg2) {
  return window['go']['main']['App']['ApplyMirrorFavoriteToCharacter'](arg1, arg2);
}

export function ApplyPresetToCharacter(arg1, arg2) {
  return window['go']['main']['App']['ApplyPresetToCharacter'](arg1, arg2);
}

export function ApplyPvPPreparation(arg1, arg2) {
  return window['go']['main']['App']['ApplyPvPPreparation'](arg1, arg2);
}

export function ApplyRepairsLoaded(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyRepairsLoaded'](arg1, arg2, arg3);
}

export function AuditLoadedSaveIssues() {
  return window['go']['main']['App']['AuditLoadedSaveIssues']();
}

export function BackupCurrentSave() {
  return window['go']['main']['App']['BackupCurrentSave']();
}

export function BulkSetBellBearings(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkSetBellBearings'](arg1, arg2, arg3);
}

export function BulkSetCookbooksUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkSetCookbooksUnlocked'](arg1, arg2, arg3);
}

export function BulkSetGesturesUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkSetGesturesUnlocked'](arg1, arg2, arg3);
}

export function BulkSetUnlockedRegions(arg1, arg2) {
  return window['go']['main']['App']['BulkSetUnlockedRegions'](arg1, arg2);
}

export function CleanResidualSlot(arg1) {
  return window['go']['main']['App']['CleanResidualSlot'](arg1);
}

export function CleanResidualSlots() {
  return window['go']['main']['App']['CleanResidualSlots']();
}

export function CloneSlot(arg1, arg2) {
  return window['go']['main']['App']['CloneSlot'](arg1, arg2);
}

export function CloseAndDownload(arg1) {
  return window['go']['main']['App']['CloseAndDownload'](arg1);
}

export function CloseRemoteGame(arg1) {
  return window['go']['main']['App']['CloseRemoteGame'](arg1);
}

export function CloseSave() {
  return window['go']['main']['App']['CloseSave']();
}

export function CreateManualBackup(arg1) {
  return window['go']['main']['App']['CreateManualBackup'](arg1);
}

export function DeleteBuildTemplateFromLibrary(arg1) {
  return window['go']['main']['App']['DeleteBuildTemplateFromLibrary'](arg1);
}

export function DeleteDeployTarget(arg1) {
  return window['go']['main']['App']['DeleteDeployTarget'](arg1);
}

export function DeleteSaveBackup(arg1, arg2) {
  return window['go']['main']['App']['DeleteSaveBackup'](arg1, arg2);
}

export function DeleteSlot(arg1) {
  return window['go']['main']['App']['DeleteSlot'](arg1);
}

export function DeployAndLaunch(arg1) {
  return window['go']['main']['App']['DeployAndLaunch'](arg1);
}

export function DeploySave(arg1) {
  return window['go']['main']['App']['DeploySave'](arg1);
}

export function DiagnosticRecoveryStatus() {
  return window['go']['main']['App']['DiagnosticRecoveryStatus']();
}

export function DiscardInventoryEditSession(arg1) {
  return window['go']['main']['App']['DiscardInventoryEditSession'](arg1);
}

export function DownloadBackupFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadBackupFile'](arg1, arg2);
}

export function DownloadRemoteSave(arg1) {
  return window['go']['main']['App']['DownloadRemoteSave'](arg1);
}

export function ExecuteConversion(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteConversion'](arg1, arg2, arg3);
}

export function ExecuteGaItemDuplicateRepair(arg1) {
  return window['go']['main']['App']['ExecuteGaItemDuplicateRepair'](arg1);
}

export function ExecuteGaItemRepack(arg1) {
  return window['go']['main']['App']['ExecuteGaItemRepack'](arg1);
}

export function ExportBuildTemplateV2JSONFromCharacter(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportBuildTemplateV2JSONFromCharacter'](arg1, arg2, arg3);
}

export function ExportBuildTemplateV2YAMLFromCharacter(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportBuildTemplateV2YAMLFromCharacter'](arg1, arg2, arg3);
}

export function ExportDiagnosticLog(arg1) {
  return window['go']['main']['App']['ExportDiagnosticLog'](arg1);
}

export function ExportLibraryBuildTemplateAsYAMLToFile(arg1) {
  return window['go']['main']['App']['ExportLibraryBuildTemplateAsYAMLToFile'](arg1);
}

export function GetActiveInventoryEditSessionForCharacter(arg1) {
  return window['go']['main']['App']['GetActiveInventoryEditSessionForCharacter'](arg1);
}

export function GetActiveSlots() {
  return window['go']['main']['App']['GetActiveSlots']();
}

export function GetAoWAvailability(arg1) {
  return window['go']['main']['App']['GetAoWAvailability'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBellBearings(arg1) {
  return window['go']['main']['App']['GetBellBearings'](arg1);
}

export function GetBosses(arg1) {
  return window['go']['main']['App']['GetBosses'](arg1);
}

export function GetBuildTemplateLibraryPath() {
  return window['go']['main']['App']['GetBuildTemplateLibraryPath']();
}

export function GetBuiltinCharacterPreset(arg1) {
  return window['go']['main']['App']['GetBuiltinCharacterPreset'](arg1);
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetCharacterAppearancePreset(arg1) {
  return window['go']['main']['App']['GetCharacterAppearancePreset'](arg1);
}

export function GetCharacterNames() {
  return window['go']['main']['App']['GetCharacterNames']();
}

export function GetColosseums(arg1) {
  return window['go']['main']['App']['GetColosseums'](arg1);
}

export function GetCookbooks(arg1) {
  return window['go']['main']['App']['GetCookbooks'](arg1);
}

export function GetDeployTargets() {
  return window['go']['main']['App']['GetDeployTargets']();
}

export function GetDiagnosticLogTail() {
  return window['go']['main']['App']['GetDiagnosticLogTail']();
}

export function GetFavoritesStatus() {
  return window['go']['main']['App']['GetFavoritesStatus']();
}

export function GetGestures(arg1) {
  return window['go']['main']['App']['GetGestures'](arg1);
}

export function GetGraces(arg1) {
  return window['go']['main']['App']['GetGraces'](arg1);
}

export function GetInfuseTypes() {
  return window['go']['main']['App']['GetInfuseTypes']();
}

export function GetInventoryEditSession(arg1) {
  return window['go']['main']['App']['GetInventoryEditSession'](arg1);
}

export function GetInventoryOrder(arg1, arg2) {
  return window['go']['main']['App']['GetInventoryOrder'](arg1, arg2);
}

export function GetItemDetail(arg1) {
  return window['go']['main']['App']['GetItemDetail'](arg1);
}

export function GetItemList(arg1) {
  return window['go']['main']['App']['GetItemList'](arg1);
}

export function GetItemListChunk(arg1) {
  return window['go']['main']['App']['GetItemListChunk'](arg1);
}

export function GetMapProgress(arg1) {
  return window['go']['main']['App']['GetMapProgress'](arg1);
}

export function GetNetworkParams() {
  return window['go']['main']['App']['GetNetworkParams']();
}

export function GetNetworkPreset(arg1) {
  return window['go']['main']['App']['GetNetworkPreset'](arg1);
}

export function GetQuestNPCs() {
  return window['go']['main']['App']['GetQuestNPCs']();
}

export function GetQuestProgress(arg1, arg2) {
  return window['go']['main']['App']['GetQuestProgress'](arg1, arg2);
}

export function GetSaveInventoryIntegrityReport() {
  return window['go']['main']['App']['GetSaveInventoryIntegrityReport']();
}

export function GetSlotCapacity(arg1) {
  return window['go']['main']['App']['GetSlotCapacity'](arg1);
}

export function GetSlotStates() {
  return window['go']['main']['App']['GetSlotStates']();
}

export function GetStartingClasses() {
  return window['go']['main']['App']['GetStartingClasses']();
}

export function GetSteamIDString() {
  return window['go']['main']['App']['GetSteamIDString']();
}

export function GetStorageOrder(arg1, arg2) {
  return window['go']['main']['App']['GetStorageOrder'](arg1, arg2);
}

export function GetSummoningPools(arg1) {
  return window['go']['main']['App']['GetSummoningPools'](arg1);
}

export function GetUndoDepth(arg1) {
  return window['go']['main']['App']['GetUndoDepth'](arg1);
}

export function GetUnlockedRegions(arg1) {
  return window['go']['main']['App']['GetUnlockedRegions'](arg1);
}

export function GetWeaponInventoryOrder(arg1) {
  return window['go']['main']['App']['GetWeaponInventoryOrder'](arg1);
}

export function GetWhetblades(arg1) {
  return window['go']['main']['App']['GetWhetblades'](arg1);
}

export function LaunchRemoteGame(arg1) {
  return window['go']['main']['App']['LaunchRemoteGame'](arg1);
}

export function ListAppearancePresets() {
  return window['go']['main']['App']['ListAppearancePresets']();
}

export function ListBuildTemplateLibrary() {
  return window['go']['main']['App']['ListBuildTemplateLibrary']();
}

export function ListBuiltinCharacterPresets() {
  return window['go']['main']['App']['ListBuiltinCharacterPresets']();
}

export function ListSaveBackups(arg1) {
  return window['go']['main']['App']['ListSaveBackups'](arg1);
}

export function LoadSaveFromPath(arg1) {
  return window['go']['main']['App']['LoadSaveFromPath'](arg1);
}

export function MoveInventoryWorkspaceItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveInventoryWorkspaceItem'](arg1, arg2, arg3, arg4);
}

export function MoveItemsBetweenInventoryAndStorage(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveItemsBetweenInventoryAndStorage'](arg1, arg2, arg3);
}

export function PrepareConversion() {
  return window['go']['main']['App']['PrepareConversion']();
}

export function PreviewBuildTemplateFromLibrary(arg1) {
  return window['go']['main']['App']['PreviewBuildTemplateFromLibrary'](arg1);
}

export function PreviewBuildTemplateImportYAMLFromFile() {
  return window['go']['main']['App']['PreviewBuildTemplateImportYAMLFromFile']();
}

export function PreviewBuildTemplateImportYAMLFromURL(arg1) {
  return window['go']['main']['App']['PreviewBuildTemplateImportYAMLFromURL'](arg1);
}

export function PreviewBuildTemplateV2FromCharacter(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewBuildTemplateV2FromCharacter'](arg1, arg2, arg3);
}

export function RebuildBuildTemplateLibraryIndex() {
  return window['go']['main']['App']['RebuildBuildTemplateLibraryIndex']();
}

export function RecordDiagnosticClientError(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordDiagnosticClientError'](arg1, arg2, arg3);
}

export function RemoveFavoritePreset(arg1) {
  return window['go']['main']['App']['RemoveFavoritePreset'](arg1);
}

export function RemoveFogOfWar(arg1) {
  return window['go']['main']['App']['RemoveFogOfWar'](arg1);
}

export function RemoveInventoryWorkspaceItem(arg1, arg2) {
  return window['go']['main']['App']['RemoveInventoryWorkspaceItem'](arg1, arg2);
}

export function RemoveItemsFromCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoveItemsFromCharacter'](arg1, arg2, arg3, arg4);
}

export function RenameBuildTemplateInLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameBuildTemplateInLibrary'](arg1, arg2, arg3, arg4);
}

export function ReorderInventory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderInventory'](arg1, arg2, arg3);
}

export function ReorderInventoryWorkspaceItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderInventoryWorkspaceItems'](arg1, arg2, arg3);
}

export function ReorderStorage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderStorage'](arg1, arg2, arg3);
}

export function ReorderWeaponInventory(arg1, arg2) {
  return window['go']['main']['App']['ReorderWeaponInventory'](arg1, arg2);
}

export function RepairAllLoadedSlots() {
  return window['go']['main']['App']['RepairAllLoadedSlots']();
}

export function RepairAllWeaponIssues(arg1) {
  return window['go']['main']['App']['RepairAllWeaponIssues'](arg1);
}

export function RepairDuplicateInventoryIndices(arg1) {
  return window['go']['main']['App']['RepairDuplicateInventoryIndices'](arg1);
}

export function RepairInventoryWorkspaceItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['RepairInventoryWorkspaceItem'](arg1, arg2, arg3);
}

export function RepairInventoryWorkspaceItems(arg1, arg2) {
  return window['go']['main']['App']['RepairInventoryWorkspaceItems'](arg1, arg2);
}

export function ResetMapExploration(arg1) {
  return window['go']['main']['App']['ResetMapExploration'](arg1);
}

export function ResetNetworkParams() {
  return window['go']['main']['App']['ResetNetworkParams']();
}

export function RevealAllMap(arg1) {
  return window['go']['main']['App']['RevealAllMap'](arg1);
}

export function RevertSlot(arg1) {
  return window['go']['main']['App']['RevertSlot'](arg1);
}

export function RunDiagnosticsAllLoaded() {
  return window['go']['main']['App']['RunDiagnosticsAllLoaded']();
}

export function SaveBuildTemplateToLibrary(arg1, arg2) {
  return window['go']['main']['App']['SaveBuildTemplateToLibrary'](arg1, arg2);
}

export function SaveBuildTemplateV2FromCharacterToLibrary(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveBuildTemplateV2FromCharacterToLibrary'](arg1, arg2, arg3);
}

export function SaveCharacter(arg1, arg2) {
  return window['go']['main']['App']['SaveCharacter'](arg1, arg2);
}

export function SaveDeployTarget(arg1) {
  return window['go']['main']['App']['SaveDeployTarget'](arg1);
}

export function SaveImportedBuildTemplateJSONToLibrary(arg1) {
  return window['go']['main']['App']['SaveImportedBuildTemplateJSONToLibrary'](arg1);
}

export function SaveInventoryWorkspaceChanges(arg1) {
  return window['go']['main']['App']['SaveInventoryWorkspaceChanges'](arg1);
}

export function ScanInventoryIssues(arg1) {
  return window['go']['main']['App']['ScanInventoryIssues'](arg1);
}

export function ScanRepairIssuesLoaded(arg1) {
  return window['go']['main']['App']['ScanRepairIssuesLoaded'](arg1);
}

export function SelectAndOpenSave() {
  return window['go']['main']['App']['SelectAndOpenSave']();
}

export function SetActiveBackup(arg1, arg2) {
  return window['go']['main']['App']['SetActiveBackup'](arg1, arg2);
}

export function SetBellBearingUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBellBearingUnlocked'](arg1, arg2, arg3);
}

export function SetBossDefeated(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBossDefeated'](arg1, arg2, arg3);
}

export function SetCharacterGender(arg1, arg2) {
  return window['go']['main']['App']['SetCharacterGender'](arg1, arg2);
}

export function SetColosseumUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetColosseumUnlocked'](arg1, arg2, arg3);
}

export function SetCookbookUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCookbookUnlocked'](arg1, arg2, arg3);
}

export function SetDiagnosticDebugMode(arg1) {
  return window['go']['main']['App']['SetDiagnosticDebugMode'](arg1);
}

export function SetGestureUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGestureUnlocked'](arg1, arg2, arg3);
}

export function SetGraceVisited(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGraceVisited'](arg1, arg2, arg3);
}

export function SetMapFlag(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMapFlag'](arg1, arg2, arg3);
}

export function SetMapRegionFlags(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMapRegionFlags'](arg1, arg2, arg3);
}

export function SetNetworkParams(arg1) {
  return window['go']['main']['App']['SetNetworkParams'](arg1);
}

export function SetQuestStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetQuestStep'](arg1, arg2, arg3);
}

export function SetRegionUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRegionUnlocked'](arg1, arg2, arg3);
}

export function SetSlotActivity(arg1, arg2) {
  return window['go']['main']['App']['SetSlotActivity'](arg1, arg2);
}

export function SetSteamIDFromString(arg1) {
  return window['go']['main']['App']['SetSteamIDFromString'](arg1);
}

export function SetSummoningPoolActivated(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSummoningPoolActivated'](arg1, arg2, arg3);
}

export function SetWhetbladeUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWhetbladeUnlocked'](arg1, arg2, arg3);
}

export function StartInventoryEditSession(arg1) {
  return window['go']['main']['App']['StartInventoryEditSession'](arg1);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function TransferInventoryWorkspaceItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransferInventoryWorkspaceItem'](arg1, arg2, arg3);
}

export function UnsetActiveBackup(arg1) {
  return window['go']['main']['App']['UnsetActiveBackup'](arg1);
}

export function UpdateBackupMeta(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateBackupMeta'](arg1, arg2, arg3, arg4);
}

export function UpdateInventoryWorkspaceWeapon(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateInventoryWorkspaceWeapon'](arg1, arg2, arg3);
}

export function ValidateBuiltinCharacterPreset(arg1, arg2) {
  return window['go']['main']['App']['ValidateBuiltinCharacterPreset'](arg1, arg2);
}

export function ValidateInventoryWorkspace(arg1) {
  return window['go']['main']['App']['ValidateInventoryWorkspace'](arg1);
}

export function WriteSave() {
  return window['go']['main']['App']['WriteSave']();
}

export function WriteSelectedToFavorites(arg1, arg2) {
  return window['go']['main']['App']['WriteSelectedToFavorites'](arg1, arg2);
}
