// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {editor} from '../models';
import {main} from '../models';
import {vm} from '../models';
import {db} from '../models';
import {deploy} from '../models';
import {core} from '../models';
import {templates} from '../models';

export function AddInventoryWorkspaceItem(arg1:string,arg2:editor.AddItemSpec,arg3:string,arg4:number):Promise<editor.InventoryWorkspaceSnapshot>;

export function AddItemsToCharacter(arg1:number,arg2:Array<number>,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number):Promise<main.AddResult>;

export function ApplyBuildTemplateFromLibrary(arg1:string,arg2:string,arg3:main.ApplyTemplateOptions):Promise<main.ApplyTemplateResult>;

export function ApplyBuildTemplateV2FromFileToCharacter(arg1:number,arg2:main.ApplyTemplateV2Options):Promise<main.ApplyTemplateV2Result>;

export function ApplyBuildTemplateV2FromLibraryToCharacter(arg1:number,arg2:string,arg3:main.ApplyTemplateV2Options):Promise<main.ApplyTemplateV2Result>;

export function ApplyBuildTemplateV2ToCharacterJSON(arg1:number,arg2:string,arg3:main.ApplyTemplateV2Options):Promise<main.ApplyTemplateV2Result>;

export function ApplyBuiltinCharacterPresetInventory(arg1:number,arg2:string):Promise<vm.PresetApplyResult>;

export function ApplyBuiltinCharacterPresetStats(arg1:number,arg2:string):Promise<vm.PresetApplyResult>;

export function ApplyMirrorFavoriteToCharacter(arg1:number,arg2:number):Promise<void>;

export function ApplyPresetToCharacter(arg1:number,arg2:string):Promise<void>;

export function ApplyPvPPreparation(arg1:number,arg2:main.PvPPreparationOptions):Promise<Array<string>>;

export function AuditLoadedSaveIssues():Promise<Array<main.SaveIssue>>;

export function BulkSetBellBearings(arg1:number,arg2:Array<number>,arg3:boolean):Promise<void>;

export function BulkSetCookbooksUnlocked(arg1:number,arg2:Array<number>,arg3:boolean):Promise<void>;

export function BulkSetGesturesUnlocked(arg1:number,arg2:Array<number>,arg3:boolean):Promise<void>;

export function BulkSetUnlockedRegions(arg1:number,arg2:Array<number>):Promise<void>;

export function CleanResidualSlot(arg1:number):Promise<void>;

export function CleanResidualSlots():Promise<number>;

export function CloneSlot(arg1:number,arg2:number):Promise<void>;

export function CloseAndDownload(arg1:string):Promise<string>;

export function CloseRemoteGame(arg1:string):Promise<string>;

export function CloseSave():Promise<void>;

export function CreateManualBackup(arg1:string):Promise<void>;

export function DeleteBuildTemplateFromLibrary(arg1:string):Promise<void>;

export function DeleteDeployTarget(arg1:string):Promise<void>;

export function DeleteSaveBackup(arg1:string,arg2:string):Promise<void>;

export function DeleteSlot(arg1:number):Promise<void>;

export function DeployAndLaunch(arg1:string):Promise<void>;

export function DeploySave(arg1:string):Promise<string>;

export function DiscardInventoryEditSession(arg1:string):Promise<void>;

export function DownloadBackupFile(arg1:string,arg2:string):Promise<string>;

export function DownloadRemoteSave(arg1:string):Promise<string>;

export function ExecuteConversion(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportBuildTemplateV2JSONFromCharacter(arg1:number,arg2:string,arg3:main.BuildTemplateV2ExportOptions):Promise<string>;

export function ExportBuildTemplateV2YAMLFromCharacter(arg1:number,arg2:string,arg3:main.BuildTemplateV2ExportOptions):Promise<string>;

export function ExportLibraryBuildTemplateAsYAMLToFile(arg1:string):Promise<main.BuildTemplateExportResult>;

export function GetActiveInventoryEditSessionForCharacter(arg1:number):Promise<main.ActiveInventoryEditSession>;

export function GetActiveSlots():Promise<Array<boolean>>;

export function GetAoWAvailability(arg1:number):Promise<Array<vm.AoWAvailabilityEntry>>;

export function GetAppVersion():Promise<string>;

export function GetBellBearings(arg1:number):Promise<Array<db.BellBearingEntry>>;

export function GetBosses(arg1:number):Promise<Array<db.BossEntry>>;

export function GetBuildTemplateLibraryPath():Promise<string>;

export function GetBuiltinCharacterPreset(arg1:string):Promise<vm.CharacterPreset>;

export function GetCharacter(arg1:number):Promise<vm.CharacterViewModel>;

export function GetCharacterNames():Promise<Array<string>>;

export function GetColosseums(arg1:number):Promise<Array<db.ColosseumEntry>>;

export function GetCookbooks(arg1:number):Promise<Array<db.CookbookEntry>>;

export function GetDeployTargets():Promise<Array<deploy.Target>>;

export function GetFavoritesStatus():Promise<Array<main.FavoriteSlotInfo>>;

export function GetGestures(arg1:number):Promise<Array<db.GestureEntry>>;

export function GetGraces(arg1:number):Promise<Array<db.GraceEntry>>;

export function GetInfuseTypes():Promise<Array<db.InfuseType>>;

export function GetInventoryEditSession(arg1:string):Promise<editor.InventoryWorkspaceSnapshot>;

export function GetInventoryOrder(arg1:number,arg2:string):Promise<Array<main.InventoryOrderItem>>;

export function GetItemDetail(arg1:number):Promise<db.ItemEntry>;

export function GetItemList(arg1:string):Promise<Array<db.ItemEntry>>;

export function GetItemListChunk(arg1:string):Promise<Array<db.ItemEntry>>;

export function GetMapProgress(arg1:number):Promise<Array<db.MapEntry>>;

export function GetNetworkParams():Promise<core.NetworkParamValues>;

export function GetNetworkPreset(arg1:string):Promise<core.NetworkParamValues>;

export function GetQuestNPCs():Promise<Array<string>>;

export function GetQuestProgress(arg1:number,arg2:string):Promise<db.QuestNPC>;

export function GetSaveInventoryIntegrityReport():Promise<main.SaveInventoryIntegrityReport>;

export function GetSlotCapacity(arg1:number):Promise<main.SlotCapacity>;

export function GetSlotStates():Promise<Array<main.SlotState>>;

export function GetStartingClasses():Promise<Array<db.ClassStats>>;

export function GetSteamIDString():Promise<string>;

export function GetStorageOrder(arg1:number,arg2:string):Promise<Array<main.InventoryOrderItem>>;

export function GetSummoningPools(arg1:number):Promise<Array<db.SummoningPoolEntry>>;

export function GetUndoDepth(arg1:number):Promise<number>;

export function GetUnlockedRegions(arg1:number):Promise<Array<db.RegionEntry>>;

export function GetWeaponInventoryOrder(arg1:number):Promise<Array<main.InventoryOrderItem>>;

export function GetWhetblades(arg1:number):Promise<Array<db.WhetbladeEntry>>;

export function LaunchRemoteGame(arg1:string):Promise<string>;

export function ListAppearancePresets():Promise<Array<main.PresetInfo>>;

export function ListBuildTemplateLibrary():Promise<Array<templates.LibraryTemplateEntry>>;

export function ListBuiltinCharacterPresets():Promise<Array<main.BuiltinCharacterPresetInfo>>;

export function ListSaveBackups(arg1:string):Promise<Array<deploy.SaveBackupEntry>>;

export function LoadSaveFromPath(arg1:string):Promise<string>;

export function MoveInventoryWorkspaceItem(arg1:string,arg2:string,arg3:string,arg4:number):Promise<editor.InventoryWorkspaceSnapshot>;

export function MoveItemsBetweenInventoryAndStorage(arg1:number,arg2:Array<number>,arg3:string):Promise<core.TransferResult>;

export function PickDiagnosticsFile():Promise<string>;

export function PrepareConversion():Promise<main.ConversionInfo>;

export function PreviewBuildTemplateFromLibrary(arg1:string):Promise<main.LoadedTemplatePreview>;

export function PreviewBuildTemplateImportYAMLFromFile():Promise<main.LoadedTemplatePreview>;

export function PreviewBuildTemplateImportYAMLFromURL(arg1:string):Promise<main.LoadedTemplatePreview>;

export function PreviewBuildTemplateV2FromCharacter(arg1:number,arg2:string,arg3:main.BuildTemplateV2ExportOptions):Promise<main.LoadedTemplatePreview>;

export function RebuildBuildTemplateLibraryIndex():Promise<Array<templates.LibraryTemplateEntry>>;

export function RemoveFavoritePreset(arg1:number):Promise<void>;

export function RemoveFogOfWar(arg1:number):Promise<void>;

export function RemoveInventoryWorkspaceItem(arg1:string,arg2:string):Promise<editor.InventoryWorkspaceSnapshot>;

export function RemoveItemsFromCharacter(arg1:number,arg2:Array<number>,arg3:boolean,arg4:boolean):Promise<void>;

export function RenameBuildTemplateInLibrary(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<templates.LibraryTemplateEntry>;

export function ReorderInventory(arg1:number,arg2:string,arg3:Array<number>):Promise<void>;

export function ReorderStorage(arg1:number,arg2:string,arg3:Array<number>):Promise<void>;

export function ReorderWeaponInventory(arg1:number,arg2:Array<number>):Promise<void>;

export function RepairAllLoadedSlots():Promise<main.RepairReport>;

export function RepairDuplicateInventoryIndices(arg1:number):Promise<core.InventoryIndexRepairReport>;

export function RepairExternal():Promise<main.RepairReport>;

export function RepairLoadedSave(arg1:number):Promise<main.RepairReport>;

export function ResetMapExploration(arg1:number):Promise<void>;

export function ResetNetworkParams():Promise<void>;

export function RevealAllMap(arg1:number):Promise<void>;

export function RevertSlot(arg1:number):Promise<void>;

export function RunDiagnosticsAllLoaded():Promise<main.DiagnosticsReport>;

export function RunDiagnosticsExternal(arg1:string):Promise<main.DiagnosticsReport>;

export function RunDiagnosticsLoaded(arg1:number):Promise<main.DiagnosticsReport>;

export function SaveBuildTemplateToLibrary(arg1:string,arg2:main.BuildTemplateExportOptions):Promise<templates.LibraryTemplateEntry>;

export function SaveBuildTemplateV2FromCharacterToLibrary(arg1:number,arg2:string,arg3:main.BuildTemplateV2ExportOptions):Promise<templates.LibraryTemplateEntry>;

export function SaveCharacter(arg1:number,arg2:vm.CharacterViewModel):Promise<void>;

export function SaveDeployTarget(arg1:deploy.Target):Promise<void>;

export function SaveImportedBuildTemplateJSONToLibrary(arg1:string):Promise<templates.LibraryTemplateEntry>;

export function SaveInventoryWorkspaceChanges(arg1:string):Promise<editor.InventoryWorkspaceSnapshot>;

export function SaveRepairedExternal(arg1:string):Promise<string>;

export function SelectAndOpenSave():Promise<string>;

export function SetActiveBackup(arg1:string,arg2:string):Promise<void>;

export function SetBellBearingUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetBossDefeated(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetCharacterGender(arg1:number,arg2:number):Promise<void>;

export function SetColosseumUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetCookbookUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetGestureUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetGraceVisited(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetMapFlag(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetMapRegionFlags(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetNetworkParams(arg1:core.NetworkParamValues):Promise<void>;

export function SetQuestStep(arg1:number,arg2:string,arg3:number):Promise<void>;

export function SetRegionUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetSlotActivity(arg1:number,arg2:boolean):Promise<void>;

export function SetSteamIDFromString(arg1:string):Promise<void>;

export function SetSummoningPoolActivated(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetWhetbladeUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<boolean>;

export function StartInventoryEditSession(arg1:number):Promise<editor.InventoryWorkspaceSnapshot>;

export function TestSSHConnection(arg1:string):Promise<string>;

export function TransferInventoryWorkspaceItem(arg1:string,arg2:string,arg3:string):Promise<editor.InventoryWorkspaceSnapshot>;

export function UnsetActiveBackup(arg1:string):Promise<void>;

export function UpdateBackupMeta(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function UpdateInventoryWorkspaceWeapon(arg1:string,arg2:string,arg3:editor.WeaponPatch):Promise<editor.InventoryWorkspaceSnapshot>;

export function ValidateBuiltinCharacterPreset(arg1:number,arg2:string):Promise<Array<string>>;

export function ValidateInventoryWorkspace(arg1:string):Promise<editor.WorkspaceValidationReport>;

export function WriteSave():Promise<void>;

export function WriteSelectedToFavorites(arg1:number,arg2:Array<string>):Promise<number>;
