// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {vm} from '../models';
import {core} from '../models';
import {db} from '../models';
import {deploy} from '../models';

export function AddItemsToCharacter(arg1:number,arg2:Array<number>,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number):Promise<main.AddResult>;

export function ApplyCharacterPreset(arg1:number,arg2:vm.CharacterPreset,arg3:vm.ApplyOptions):Promise<vm.PresetApplyResult>;

export function ApplyMirrorFavoriteToCharacter(arg1:number,arg2:number):Promise<void>;

export function BulkSetAshOfWarFlags(arg1:number,arg2:Array<number>,arg3:boolean):Promise<void>;

export function BulkSetBellBearings(arg1:number,arg2:Array<number>,arg3:boolean):Promise<void>;

export function BulkSetCookbooksUnlocked(arg1:number,arg2:Array<number>,arg3:boolean):Promise<void>;

export function BulkSetGesturesUnlocked(arg1:number,arg2:Array<number>,arg3:boolean):Promise<void>;

export function BulkSetUnlockedRegions(arg1:number,arg2:Array<number>):Promise<void>;

export function CloneSlot(arg1:number,arg2:number):Promise<void>;

export function CloseAndDownload(arg1:string):Promise<string>;

export function CloseRemoteGame(arg1:string):Promise<string>;

export function DeleteDeployTarget(arg1:string):Promise<void>;

export function DeleteSlot(arg1:number):Promise<void>;

export function DeployAndLaunch(arg1:string):Promise<void>;

export function DeploySave(arg1:string):Promise<string>;

export function DiagnoseAllSlots():Promise<Array<core.SlotDiagnostics>>;

export function DiagnoseSlot(arg1:number):Promise<core.SlotDiagnostics>;

export function DownloadRemoteSave(arg1:string):Promise<string>;

export function ExportCharacterPresetToFile(arg1:number):Promise<string>;

export function GetActiveSlots():Promise<Array<boolean>>;

export function GetAllGraces():Promise<Array<db.GraceEntry>>;

export function GetAshOfWarFlags(arg1:number):Promise<Array<db.AshOfWarFlagEntry>>;

export function GetBellBearings(arg1:number):Promise<Array<db.BellBearingEntry>>;

export function GetBosses(arg1:number):Promise<Array<db.BossEntry>>;

export function GetCharacter(arg1:number):Promise<vm.CharacterViewModel>;

export function GetCharacterNames():Promise<Array<string>>;

export function GetColosseums(arg1:number):Promise<Array<db.ColosseumEntry>>;

export function GetCookbooks(arg1:number):Promise<Array<db.CookbookEntry>>;

export function GetDeployTargets():Promise<Array<deploy.Target>>;

export function GetFavoritesStatus():Promise<Array<main.FavoriteSlotInfo>>;

export function GetGestures(arg1:number):Promise<Array<db.GestureEntry>>;

export function GetGraces(arg1:number):Promise<Array<db.GraceEntry>>;

export function GetInfuseTypes():Promise<Array<db.InfuseType>>;

export function GetItemDetail(arg1:number):Promise<db.ItemEntry>;

export function GetItemList(arg1:string):Promise<Array<db.ItemEntry>>;

export function GetItemListChunk(arg1:string):Promise<Array<db.ItemEntry>>;

export function GetMapProgress(arg1:number):Promise<Array<db.MapEntry>>;

export function GetNetworkParams():Promise<core.NetworkParamValues>;

export function GetNetworkPreset(arg1:string):Promise<core.NetworkParamValues>;

export function GetQuestNPCs():Promise<Array<string>>;

export function GetQuestProgress(arg1:number,arg2:string):Promise<db.QuestNPC>;

export function GetSaveDiffSummary():Promise<Array<main.SlotDiffSummary>>;

export function GetSlotCapacity(arg1:number):Promise<main.SlotCapacity>;

export function GetSlotDiff(arg1:number):Promise<Array<main.DiffEntry>>;

export function GetSourceActiveSlots():Promise<Array<boolean>>;

export function GetSteamID():Promise<number>;

export function GetSteamIDString():Promise<string>;

export function GetSummoningPools(arg1:number):Promise<Array<db.SummoningPoolEntry>>;

export function GetUndoDepth(arg1:number):Promise<number>;

export function GetUnlockedRegions(arg1:number):Promise<Array<db.RegionEntry>>;

export function GetWhetblades(arg1:number):Promise<Array<db.WhetbladeEntry>>;

export function ImportCharacter(arg1:number,arg2:number):Promise<void>;

export function LaunchRemoteGame(arg1:string):Promise<string>;

export function ListAppearancePresets():Promise<Array<main.PresetInfo>>;

export function LoadCharacterPresetFromFile():Promise<vm.CharacterPreset>;

export function LoadCharacterPresetFromURL(arg1:string):Promise<vm.CharacterPreset>;

export function RemoveFavoritePreset(arg1:number):Promise<void>;

export function RemoveFogOfWar(arg1:number):Promise<void>;

export function RemoveItemsFromCharacter(arg1:number,arg2:Array<number>,arg3:boolean,arg4:boolean):Promise<void>;

export function RepairInventoryGaItems(arg1:number):Promise<number>;

export function ResetMapExploration(arg1:number):Promise<void>;

export function ResetNetworkParams():Promise<void>;

export function RevealAllMap(arg1:number):Promise<void>;

export function RevertSlot(arg1:number):Promise<void>;

export function SaveCharacter(arg1:number,arg2:vm.CharacterViewModel):Promise<void>;

export function SaveDeployTarget(arg1:deploy.Target):Promise<void>;

export function SelectAndOpenSave():Promise<string>;

export function SelectAndOpenSourceSave():Promise<string>;

export function SetAshOfWarFlagUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetBellBearingUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetBossDefeated(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetColosseumUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetCookbookUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetGestureUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetGraceVisited(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetMapFlag(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetMapRegionFlags(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetNetworkParams(arg1:core.NetworkParamValues):Promise<void>;

export function SetQuestStep(arg1:number,arg2:string,arg3:number):Promise<void>;

export function SetRegionUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetSlotActivity(arg1:number,arg2:boolean):Promise<void>;

export function SetSteamID(arg1:number):Promise<void>;

export function SetSteamIDFromString(arg1:string):Promise<void>;

export function SetSummoningPoolActivated(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetWhetbladeUnlocked(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function TestSSHConnection(arg1:string):Promise<string>;

export function ValidateCharacterPreset(arg1:vm.CharacterPreset):Promise<Array<string>>;

export function WriteSave(arg1:string):Promise<void>;

export function WriteSelectedToFavorites(arg1:number,arg2:Array<string>):Promise<number>;
