// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItemsToCharacter(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddItemsToCharacter'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ApplyBuiltinCharacterPresetStats(arg1, arg2) {
  return window['go']['main']['App']['ApplyBuiltinCharacterPresetStats'](arg1, arg2);
}

export function ApplyCharacterPreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyCharacterPreset'](arg1, arg2, arg3);
}

export function ApplyMirrorFavoriteToCharacter(arg1, arg2) {
  return window['go']['main']['App']['ApplyMirrorFavoriteToCharacter'](arg1, arg2);
}

export function ApplyPresetToCharacter(arg1, arg2) {
  return window['go']['main']['App']['ApplyPresetToCharacter'](arg1, arg2);
}

export function ApplyPvPPreparation(arg1, arg2) {
  return window['go']['main']['App']['ApplyPvPPreparation'](arg1, arg2);
}

export function ApplyWeaponAoW(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyWeaponAoW'](arg1, arg2, arg3);
}

export function ApplyWeaponAoWStrict(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyWeaponAoWStrict'](arg1, arg2, arg3);
}

export function ApplyWeaponInfusion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyWeaponInfusion'](arg1, arg2, arg3, arg4);
}

export function BulkSetAshOfWarFlags(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkSetAshOfWarFlags'](arg1, arg2, arg3);
}

export function BulkSetBellBearings(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkSetBellBearings'](arg1, arg2, arg3);
}

export function BulkSetCookbooksUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkSetCookbooksUnlocked'](arg1, arg2, arg3);
}

export function BulkSetGesturesUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkSetGesturesUnlocked'](arg1, arg2, arg3);
}

export function BulkSetUnlockedRegions(arg1, arg2) {
  return window['go']['main']['App']['BulkSetUnlockedRegions'](arg1, arg2);
}

export function CloneSlot(arg1, arg2) {
  return window['go']['main']['App']['CloneSlot'](arg1, arg2);
}

export function CloseAndDownload(arg1) {
  return window['go']['main']['App']['CloseAndDownload'](arg1);
}

export function CloseRemoteGame(arg1) {
  return window['go']['main']['App']['CloseRemoteGame'](arg1);
}

export function DeleteDeployTarget(arg1) {
  return window['go']['main']['App']['DeleteDeployTarget'](arg1);
}

export function DeleteSlot(arg1) {
  return window['go']['main']['App']['DeleteSlot'](arg1);
}

export function DeployAndLaunch(arg1) {
  return window['go']['main']['App']['DeployAndLaunch'](arg1);
}

export function DeploySave(arg1) {
  return window['go']['main']['App']['DeploySave'](arg1);
}

export function DownloadRemoteSave(arg1) {
  return window['go']['main']['App']['DownloadRemoteSave'](arg1);
}

export function ExportCharacterPresetToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportCharacterPresetToFile'](arg1, arg2);
}

export function GetActiveSlots() {
  return window['go']['main']['App']['GetActiveSlots']();
}

export function GetAoWAvailability(arg1) {
  return window['go']['main']['App']['GetAoWAvailability'](arg1);
}

export function GetAshOfWarFlags(arg1) {
  return window['go']['main']['App']['GetAshOfWarFlags'](arg1);
}

export function GetBellBearings(arg1) {
  return window['go']['main']['App']['GetBellBearings'](arg1);
}

export function GetBosses(arg1) {
  return window['go']['main']['App']['GetBosses'](arg1);
}

export function GetBuiltinCharacterPreset(arg1) {
  return window['go']['main']['App']['GetBuiltinCharacterPreset'](arg1);
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetCharacterNames() {
  return window['go']['main']['App']['GetCharacterNames']();
}

export function GetColosseums(arg1) {
  return window['go']['main']['App']['GetColosseums'](arg1);
}

export function GetCookbooks(arg1) {
  return window['go']['main']['App']['GetCookbooks'](arg1);
}

export function GetDeployTargets() {
  return window['go']['main']['App']['GetDeployTargets']();
}

export function GetFavoritesStatus() {
  return window['go']['main']['App']['GetFavoritesStatus']();
}

export function GetGestures(arg1) {
  return window['go']['main']['App']['GetGestures'](arg1);
}

export function GetGraces(arg1) {
  return window['go']['main']['App']['GetGraces'](arg1);
}

export function GetInfuseTypes() {
  return window['go']['main']['App']['GetInfuseTypes']();
}

export function GetItemDetail(arg1) {
  return window['go']['main']['App']['GetItemDetail'](arg1);
}

export function GetItemList(arg1) {
  return window['go']['main']['App']['GetItemList'](arg1);
}

export function GetItemListChunk(arg1) {
  return window['go']['main']['App']['GetItemListChunk'](arg1);
}

export function GetMapProgress(arg1) {
  return window['go']['main']['App']['GetMapProgress'](arg1);
}

export function GetNetworkParams() {
  return window['go']['main']['App']['GetNetworkParams']();
}

export function GetNetworkPreset(arg1) {
  return window['go']['main']['App']['GetNetworkPreset'](arg1);
}

export function GetQuestNPCs() {
  return window['go']['main']['App']['GetQuestNPCs']();
}

export function GetQuestProgress(arg1, arg2) {
  return window['go']['main']['App']['GetQuestProgress'](arg1, arg2);
}

export function GetSaveDiffSummary() {
  return window['go']['main']['App']['GetSaveDiffSummary']();
}

export function GetSlotCapacity(arg1) {
  return window['go']['main']['App']['GetSlotCapacity'](arg1);
}

export function GetSlotDiff(arg1) {
  return window['go']['main']['App']['GetSlotDiff'](arg1);
}

export function GetSourceActiveSlots() {
  return window['go']['main']['App']['GetSourceActiveSlots']();
}

export function GetStartingClasses() {
  return window['go']['main']['App']['GetStartingClasses']();
}

export function GetSteamIDString() {
  return window['go']['main']['App']['GetSteamIDString']();
}

export function GetSummoningPools(arg1) {
  return window['go']['main']['App']['GetSummoningPools'](arg1);
}

export function GetUndoDepth(arg1) {
  return window['go']['main']['App']['GetUndoDepth'](arg1);
}

export function GetUnlockedRegions(arg1) {
  return window['go']['main']['App']['GetUnlockedRegions'](arg1);
}

export function GetWhetblades(arg1) {
  return window['go']['main']['App']['GetWhetblades'](arg1);
}

export function ImportCharacter(arg1, arg2) {
  return window['go']['main']['App']['ImportCharacter'](arg1, arg2);
}

export function LaunchRemoteGame(arg1) {
  return window['go']['main']['App']['LaunchRemoteGame'](arg1);
}

export function ListAppearancePresets() {
  return window['go']['main']['App']['ListAppearancePresets']();
}

export function ListBuiltinCharacterPresets() {
  return window['go']['main']['App']['ListBuiltinCharacterPresets']();
}

export function LoadCharacterPresetFromFile() {
  return window['go']['main']['App']['LoadCharacterPresetFromFile']();
}

export function LoadCharacterPresetFromURL(arg1) {
  return window['go']['main']['App']['LoadCharacterPresetFromURL'](arg1);
}

export function RemoveFavoritePreset(arg1) {
  return window['go']['main']['App']['RemoveFavoritePreset'](arg1);
}

export function RemoveFogOfWar(arg1) {
  return window['go']['main']['App']['RemoveFogOfWar'](arg1);
}

export function RemoveItemsFromCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoveItemsFromCharacter'](arg1, arg2, arg3, arg4);
}

export function ResetMapExploration(arg1) {
  return window['go']['main']['App']['ResetMapExploration'](arg1);
}

export function ResetNetworkParams() {
  return window['go']['main']['App']['ResetNetworkParams']();
}

export function RevealAllMap(arg1) {
  return window['go']['main']['App']['RevealAllMap'](arg1);
}

export function RevertSlot(arg1) {
  return window['go']['main']['App']['RevertSlot'](arg1);
}

export function SaveCharacter(arg1, arg2) {
  return window['go']['main']['App']['SaveCharacter'](arg1, arg2);
}

export function SaveDeployTarget(arg1) {
  return window['go']['main']['App']['SaveDeployTarget'](arg1);
}

export function SelectAndOpenSave() {
  return window['go']['main']['App']['SelectAndOpenSave']();
}

export function SelectAndOpenSourceSave() {
  return window['go']['main']['App']['SelectAndOpenSourceSave']();
}

export function SetAshOfWarFlagUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAshOfWarFlagUnlocked'](arg1, arg2, arg3);
}

export function SetBellBearingUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBellBearingUnlocked'](arg1, arg2, arg3);
}

export function SetBossDefeated(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBossDefeated'](arg1, arg2, arg3);
}

export function SetCharacterGender(arg1, arg2) {
  return window['go']['main']['App']['SetCharacterGender'](arg1, arg2);
}

export function SetColosseumUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetColosseumUnlocked'](arg1, arg2, arg3);
}

export function SetCookbookUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCookbookUnlocked'](arg1, arg2, arg3);
}

export function SetGestureUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGestureUnlocked'](arg1, arg2, arg3);
}

export function SetGraceVisited(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGraceVisited'](arg1, arg2, arg3);
}

export function SetMapFlag(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMapFlag'](arg1, arg2, arg3);
}

export function SetMapRegionFlags(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMapRegionFlags'](arg1, arg2, arg3);
}

export function SetNetworkParams(arg1) {
  return window['go']['main']['App']['SetNetworkParams'](arg1);
}

export function SetQuestStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetQuestStep'](arg1, arg2, arg3);
}

export function SetRegionUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRegionUnlocked'](arg1, arg2, arg3);
}

export function SetSlotActivity(arg1, arg2) {
  return window['go']['main']['App']['SetSlotActivity'](arg1, arg2);
}

export function SetSteamIDFromString(arg1) {
  return window['go']['main']['App']['SetSteamIDFromString'](arg1);
}

export function SetSummoningPoolActivated(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSummoningPoolActivated'](arg1, arg2, arg3);
}

export function SetWhetbladeUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWhetbladeUnlocked'](arg1, arg2, arg3);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function ValidateBuiltinCharacterPreset(arg1, arg2) {
  return window['go']['main']['App']['ValidateBuiltinCharacterPreset'](arg1, arg2);
}

export function ValidateCharacterPreset(arg1) {
  return window['go']['main']['App']['ValidateCharacterPreset'](arg1);
}

export function WriteSave(arg1) {
  return window['go']['main']['App']['WriteSave'](arg1);
}

export function WriteSelectedToFavorites(arg1, arg2) {
  return window['go']['main']['App']['WriteSelectedToFavorites'](arg1, arg2);
}
